### ISSUE TITLE
Terms in Analytics vocabulary should apply to entity set instead of type

### ISSUE THREAD

**Issue by HeikoTheissen** [SAP/odata-vocabularies#91]
https://github.com/SAP/odata-vocabularies/blob/cad0f8411978c4576da810d69362b0104bb702dd/vocabularies/Analytics.xml#L79

This term should depend on the container, not on the schema. Set `AppliesTo="EntitySet Collection"` and tag with `Core.AppliesViaContainer`.

Similarly, the use of `Analytics.Dimension`, `Analytics.Measure` and `Analytics.AccumulativeMeasure` should be discouraged in favor of properties in a new term `Analytics.ApplySupported` (to be designed).

**Comment by gregorwolf** [comment]
Hello @HeikoTheissen and @ralfhandl ,

today I've learned that when I add the annotation:

```
@Aggregation.ApplySupported.Transformations      : true
```

to my sample project [sap-support-message-reporting](https://github.com/gregorwolf/sap-support-message-reporting/commit/1a9048606dc0bae210112a463b2ca0819843ccf8) it does some magic and makes the Fiori Application Generator work with this local CAP Project:

![Screenshot 2022-06-10 at 14 34 11](https://user-images.githubusercontent.com/2639535/173067891-e2414e79-abd5-41ac-9e30-3d086edb5639.png)

This issue is beside https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Aggregation.V1.md#applysupportedtype-applysupportedbase the only place where something can be found about the ApplySupported annotation. I hope this comment might help others. I know it might not be directly related to the issue.

**Comment by HeikoTheissen** [comment]
@gregorwolf, the `ApplySupported` annotation is documented [here](https://github.com/oasis-tcs/odata-vocabularies/blob/aggregation-cs03-release-candidate/vocabularies/Org.OData.Aggregation.V1.md#ApplySupported).

I close this issue now, because we decided to keep the `Analytics` terms targeting the entity type. See the closed pull request linked to this issue.

**Comment by ralfhandl** [comment]
Hi @gregorwolf,

`@Aggregation.ApplySupported` is mentioned in the UI5 documentation:
* [Configuring Charts](https://sapui5.hana.ondemand.com/sdk#/topic/653ed0f4f0d743dbb33ace4f68886c4e)
* [Setting the Table Type](https://sapui5.hana.ondemand.com/sdk#/topic/7f844f1021cd4791b8f7408eac7c1cec) in subsection "Additional Features in SAP Fiori Elements for OData V4"
